spring.datasource.url= jdbc:mysql://localhost:3306/shoppingCartDB?useSSL=false
spring.datasource.username= root
spring.datasource.password= liza990ru

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
