syntax = "proto3";
option java_multiple_files = true;
package org.example.grpc;

import "google/protobuf/empty.proto";


enum Role {
  SELLER = 0;
  BUYER = 1;
}

message SignUpRequest {
  Role role = 1;
  string login = 2;
  string password = 3;
}

message LoginRequest {
  string login = 1;
  string password = 2;
}

message LoginResponse {
  string sessionId = 1;
  Role role = 2;
}

message UpdateItemListRequest{
  string sessionId = 1;
  repeated Item item = 2;
}

message GetItemListRequest{
  string sessionId = 1;
}

message GetItemListResponse {
  repeated Item item = 1;
}

message Item{
  string name = 1;
  uint32 quantity = 2;
  uint32 invoicePriceCents = 3;
  uint32 sellPriceCents = 4;
  bool deleted = 5;
  string id = 6;
}

message Cart{
  repeated CartEntry cartEntries = 1;
}

message CartEntry{
  string itemId = 1;
  uint32 itemCount = 2;
  string itemName = 3;
  uint32 sellPrice = 4;
}

message AddItemRequest{
  string sessionId = 1;
   repeated string itemId = 2;
}

message GetCartItemListRequest{
  string sessionId = 1;
}

message GetCartItemListResponse{
  Cart cart = 1;
}

message UpdateCartRequest{
  string sessionId = 1;
  string itemId = 2;
  uint32 itemCount = 3;
}

message DeleteItemRequest{
  string sessionId = 1;
  string itemId = 2;
}

message Card{
  string cardNumber = 1;
  uint32 expMonth = 2;
  uint32 expYear = 3;
  uint32 cvv = 4;
  string cardHolderName = 5;
}

message PurchasedItem{
  string itemName = 1;
  uint32 itemCount = 2;
  uint32 pricePerUnit = 3;
}
message Order{
  string address = 1;
  repeated PurchasedItem item = 2;
  uint32 totalPaid = 3;
}

message CheckoutRequest{
  string sessionId = 1;
  string address = 2;
  Card card = 3;
}

message CheckoutResponse{
  Order order = 1;
}

message ItemProfit {
  string itemName = 1;
  int32 profit = 2; // Profit in cents
}

message GetProfitReportRequest {
  string sessionId = 1;
}

message GetProfitReportResponse {
  int32 totalProfit = 1; // Total profit in cents
  repeated ItemProfit itemProfits = 2; // Profit for each item
}

service SignUpService {
  rpc signUp(SignUpRequest) returns (google.protobuf.Empty);
}

service LoginService {
  rpc login(LoginRequest) returns (LoginResponse);
}

service SellerService {
  rpc getItemList(GetItemListRequest) returns (GetItemListResponse);
  rpc updateItemList(UpdateItemListRequest) returns (google.protobuf.Empty);
  rpc GetProfitReport(GetProfitReportRequest) returns (GetProfitReportResponse);
}

service BuyerService {
  rpc getItemList(GetItemListRequest) returns (GetItemListResponse);
  rpc getCartItemList(GetCartItemListRequest) returns (GetCartItemListResponse);
  rpc addItemToCart(AddItemRequest) returns (google.protobuf.Empty);
  rpc updateCart(UpdateCartRequest) returns (google.protobuf.Empty);
  rpc deleteItemFromCart(DeleteItemRequest) returns (google.protobuf.Empty);
  rpc checkout(CheckoutRequest) returns (CheckoutResponse);
}