syntax = "proto3";
option java_multiple_files = true;
package org.example.grpc;

import "google/protobuf/empty.proto";


enum Role {
  SELLER = 0;
  CUSTOMER = 1;
}

message SignUpRequest {
  Role role = 1;
  string login = 2;
  string password = 3;
}

message LoginRequest {
  string login = 1;
  string password = 2;
}

message LoginResponse {
  string sessionId = 1;
}

message UpdateItemListRequest{
  string sessionId = 1;
  repeated Item item = 2;
}

message GetItemListRequest{
  string sessionId = 1;
}

message GetItemListResponse {
  repeated Item item = 1;
}

message Item{
  string name = 1;
  uint32 quantity = 2;
  uint32 invoicePriceCents = 3;
  uint32 sellPriceCents = 4;
  bool deleted = 5;
  string id = 6;
}

message AddItemRequest{
  string sessionId = 1;
  string itemId = 2;
}
message UpdateCartRequest{
  string sessionId = 1;
  string itemId= 2;
  uint32 itemCount = 3;
}
message DeleteItemRequest{
  string sessionId = 1;
  string itemId = 2;
}

service SignUpService {
  rpc signUp(SignUpRequest) returns (google.protobuf.Empty);
}

service LoginService {
  rpc login(LoginRequest) returns (LoginResponse);
}

service SellerService {
  rpc getItemList(GetItemListRequest) returns (GetItemListResponse);
  rpc updateItemList(UpdateItemListRequest) returns (google.protobuf.Empty);
}
service BuyerService {
  rpc getItemList(GetItemListRequest) returns (GetItemListResponse);
  rpc addItemToCart(AddItemRequest) returns (google.protobuf.Empty);
  rpc updateCart(UpdateCartRequest) returns (google.protobuf.Empty);
  rpc deleteItemFromCart(DeleteItemRequest) returns (google.protobuf.Empty);
}